q

diff --git a/.ci/pnnx.yml b/.ci/pnnx.yml
--- a/.ci/pnnx.yml
+++ b/.ci/pnnx.yml
@@ -154,43 +154,52 @@ jobs:
         cmake --build . -j $(nproc)
         cmake --build . -j $(nproc) --target install/strip
 
-    # - name: setup-pytorch
-    #   run: |
-    #     export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
-    #     pip3 install --user torch==${{matrix.torch-version}}+cpu torchvision==${{matrix.torchvision-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
-    #     pip3 install --user onnx
-    #     pip3 install --user onnxscript
-    #
-    # - name: build-ncnn
-    #   run: |
-    #     export PATH=${{ci.workspace}}/cmake-3.29.3-linux-x86_64/bin:$PATH
-    #     export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
-    #     mkdir build && cd build
-    #     cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_PYTHON=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
-    #     cmake --build . -j $(nproc)
-    #     cd ..
-    #     export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
-    #     pip3 install --user .
-    #
-    # - name: build-pnnx
-    #   run: |
-    #     export PATH=${{ci.workspace}}/cmake-3.29.3-linux-x86_64/bin:$PATH
-    #     export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
-    #     cd tools/pnnx
-    #     mkdir build && cd build
-    #     cmake -DCMAKE_BUILD_TYPE=Release -DTorch_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-torch-install -DTorchVision_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-torch-install -Donnxruntime_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-onnx-install -Dprotobuf_DIR=${{ci.workspace}}/pnnx-deps-onnx-install/lib/cmake/protobuf ..
-    #     cmake --build . -j 16 --verbose
-    #
-    # - name: test
-    #   run: |
-    #     export PATH=${{ci.workspace}}/cmake-3.29.3-linux-x86_64/bin:$PATH
-    #     export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
-    #     export OMP_NUM_THREADS=1
-    #     export MKL_NUM_THREADS=1
-    #     export MKL_ENABLE_INSTRUCTIONS=SSE4_2
-    #     cd tools/pnnx
-    #     cd build && ctest --output-on-failure -j $(nproc)
-    #
+    - name: setup-pytorch
+      run: |
+        export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
+        pip3 install --user torch==${{matrix.torch-version}}+cpu torchvision==${{matrix.torchvision-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
+        pip3 install --user onnx
+        pip3 install --user onnxscript
+
+    - name: build-ncnn
+      run: |
+        export PATH=${{ci.workspace}}/cmake-3.29.3-linux-x86_64/bin:$PATH
+        export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
+        mkdir build && cd build
+        cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_PYTHON=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
+        cmake --build . -j $(nproc)
+        cd ..
+        export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
+        pip3 install --user .
+
+    - name: build-pnnx
+      run: |
+        export PATH=${{ci.workspace}}/cmake-3.29.3-linux-x86_64/bin:$PATH
+        export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
+        cd tools/pnnx
+        mkdir build && cd build
+        cmake -DCMAKE_BUILD_TYPE=Release -DTorch_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-torch-install -DTorchVision_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-torch-install -Donnxruntime_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-onnx-install -Dprotobuf_DIR=${{ci.workspace}}/pnnx-deps-onnx-install/lib/cmake/protobuf ..
+        cmake --build . -j 24 --verbose
+
+    - name: test
+      run: |
+        export PATH=${{ci.workspace}}/cmake-3.29.3-linux-x86_64/bin:$PATH
+        export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
+        export OMP_NUM_THREADS=1
+        export MKL_NUM_THREADS=1
+        export MKL_ENABLE_INSTRUCTIONS=SSE4_2
+        cd tools/pnnx
+        cd build
+        ctest -R test_onnx_resnet18 || true
+
+    - uses: UploadArtifactory@1.*
+      with:
+        filePath: tools/pnnx/build/tests/onnx/test_resnet18_dynamo.onnx
+
+
+
+    #    cd build && ctest --output-on-failure -j 16
+
     # - name: python-pnnx
     #   run: |
     #     export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
