debug

diff --git a/.ci/pnnx.yml b/.ci/pnnx.yml
--- a/.ci/pnnx.yml
+++ b/.ci/pnnx.yml
@@ -30,32 +30,32 @@ jobs:
           - torch-version: 1.8.1
             torchvision-version: 0.9.1
 
-          - torch-version: 1.9.1
-            torchvision-version: 0.10.1
-
-          - torch-version: 1.10.0
-            torchvision-version: 0.11.1
-
-          - torch-version: 1.11.0
-            torchvision-version: 0.12.0
-
-          - torch-version: 1.12.0
-            torchvision-version: 0.13.0
-
-          - torch-version: 1.13.0
-            torchvision-version: 0.14.0
-
-          - torch-version: 2.0.0
-            torchvision-version: 0.15.1
-
-          - torch-version: 2.1.0
-            torchvision-version: 0.16.0
-
-          - torch-version: 2.2.1
-            torchvision-version: 0.17.1
-
-          - torch-version: 2.3.0
-            torchvision-version: 0.18.0
+          # - torch-version: 1.9.1
+          #   torchvision-version: 0.10.1
+          #
+          # - torch-version: 1.10.0
+          #   torchvision-version: 0.11.1
+          #
+          # - torch-version: 1.11.0
+          #   torchvision-version: 0.12.0
+          #
+          # - torch-version: 1.12.0
+          #   torchvision-version: 0.13.0
+          #
+          # - torch-version: 1.13.0
+          #   torchvision-version: 0.14.0
+          #
+          # - torch-version: 2.0.0
+          #   torchvision-version: 0.15.1
+          #
+          # - torch-version: 2.1.0
+          #   torchvision-version: 0.16.0
+          #
+          # - torch-version: 2.2.1
+          #   torchvision-version: 0.17.1
+          #
+          # - torch-version: 2.3.0
+          #   torchvision-version: 0.18.0
 
     runs-on:
       pool-name: docker
@@ -167,9 +167,9 @@ jobs:
         export PYTHONUSERBASE=${{ci.workspace}}/torch-${{matrix.torch-version}}
         mkdir build && cd build
         cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_PYTHON=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
-        cmake --build . -j 16
+        cmake --build . -j $(nproc)
         cd ..
-        export CMAKE_BUILD_PARALLEL_LEVEL=16
+        export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
         pip3 install --user .
 
     - name: build-pnnx
@@ -179,7 +179,7 @@ jobs:
         cd tools/pnnx
         mkdir build && cd build
         cmake -DCMAKE_BUILD_TYPE=Release -DTorch_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-torch-install -DTorchVision_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-torch-install -Donnxruntime_INSTALL_DIR=${{ci.workspace}}/pnnx-deps-onnx-install -Dprotobuf_DIR=${{ci.workspace}}/pnnx-deps-onnx-install/lib/cmake/protobuf ..
-        cmake --build . -j 16
+        cmake --build . -j $(nproc)
 
     - name: test
       run: |
@@ -189,7 +189,10 @@ jobs:
         export MKL_NUM_THREADS=1
         export MKL_ENABLE_INSTRUCTIONS=SSE4_2
         cd tools/pnnx
-        cd build && ctest --output-on-failure -j 16
+        cd build
+        ctest -R test_nn_MultiheadAttention || true
+        cat tests/test_nn_MultiheadAttention_pnnx.py
+        #cd build && ctest --output-on-failure -j 16
 
     - name: python-pnnx
       run: |
